### ISSUE TITLE
Modify Radio Frequencies

### ISSUE THREAD

**Issue by oliv3lrg** [Arca-Company-Starsim/Arca-Aux-Issues#44]
**Describe the solution you'd like**
Modify existing Radio Frequencies to reflect company changes

**Long Range**
Company - LR 45
Commando Platoon - LR 40
Alpha Platoon - LR 41
X-Ray - 50

**Alpha Platoon**
Command - SR 100
Squad 1 - SR 101
Squad 2 - SR 102
Squad 3 - SR 103
Squad 4 - SR 104

**Commando Squad**
Command - SR 200
Squad 1 - SR 201
Squad 2 - SR 202
Squad 3 - SR 203
Squad 4 - SR 204
Squad 5 - SR 205

**Comment by m0kka** [comment]
Also update 3den attributes to use "anonymous" squad names

**Comment by m0kka** [comment]
done
