### ISSUE TITLE
Add Heavy RPS-6

### ISSUE THREAD

**Issue by oliv3lrg** [Arca-Company-Starsim/Arca-Aux-Issues#72]
Using the [3AS] RPS6 Heavy Projectile (3AS_RPS6_HP), add our own version of the Heavy RPS-6, capable of locking onto heat signatures and also ranging dumbfire shots (as per the vanilla NLAW) if no lock is available.

Damage should be a middle ground between our RPS-6 and PLX.

**Comment by m0kka** [comment]
added with next update
