### ISSUE TITLE
Covert Ops UAV Drone

### ISSUE THREAD

**Issue by JakubPii** [Arca-Company-Starsim/Arca-Aux-Issues#74]
**Describe the bug**
The drone strugles climing alt and does it very slowly making setting it up very long. Its also quite big making things difficult to carry so if possible we could reduce the inventory size it takes up. If we could also make it extreamly hard to detect would make it a lot more effective.

**To Reproduce**
Self Explanator

**Expected behavior**
N/A

**Screenshots**
N/A

**Mods List:**
 - Arca Company Modset: Y

**Additional context**
If possible we would like to have the drone completely unrecognisable by the Ai and if this gets abused or seemed op the feature can be removed. For more info please drop  me a dm.

**Comment by m0kka** [comment]
will do

**Comment by m0kka** [comment]
cranked some of the values, it'd be nice if you could monitor this for balance

- weight reduced to 50
- lift coefficient tripled
- camouflage improved by 600%
