### ISSUE TITLE
Defib text randomly appearing

### ISSUE THREAD

**Issue by bee-es-jay** [Arca-Company-Starsim/Arca-Aux-Issues#80]
**Describe the bug**
defib charging text appearing at the bottom of the screen when I do not have the defib

**To Reproduce**
1. Be in LAAT
2. See defib message above compass even though you don't have a defib

**Expected behavior**
defib messages to not show up when I do not have a defib

**Mods List:**
 - Arca Company Modset: Y

**Comment by m0kka** [comment]
resolved with next update
